name: Invest News Bot

on:
  schedule:
    - cron: '*/30 * * * *' # Запуск кожні 30 хвилин
  workflow_dispatch: # Дозволяє запустити скрипт вручну кнопкою

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install rss-parser @google/generative-ai

      - name: Run bot script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node bot.js
